spring:
  application:
    name: service
  flyway:
    url: jdbc:mysql://localhost:3306/cards
    user: app
    password: password
    locations: classpath:db/migration
  r2dbc:
    initialization-mode: always
    pool:
      url: r2dbc:pool:mysql://localhost:3306/cards
      username: app
      password: password
      enabled: true
      initial-size: 5
      max-size: 20
      max-idle-time: 30m
